language: node_js

branches:
  only:
    - master
    - desenvolvimento
before_install:
  - wget http://repo1.maven.org/maven2/org/codehaus/sonar/runner/sonar-runner-dist/2.4/sonar-runner-dist-2.4.zip
  - unzip sonar-runner-dist-2.4.zip

after_script:
 - ./sonar-runner-2.4/bin/sonar-runner    
